[phases.setup]
nixPkgs = ["nodejs_20", "python311", "pip"]

[phases.install]
cmds = [
  "npm install",
  "pip install pdfplumber"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm start"

